-- SSV Venture: drivers table + RLS (authenticated users only)
-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.drivers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text,
    license_number text,
    status text not null default 'Active',
    created_at timestamptz not null default now()
);

comment on table public.drivers is 'Fleet drivers; RLS restricts access to signed-in users.';

-- Row Level Security
alter table public.drivers enable row level security;

-- Full access for authenticated users (JWT role = authenticated)
create policy "drivers_authenticated_full_access"
    on public.drivers
    for all
    to authenticated
    using (true)
    with check (true);
