-- Fleet reminders (Phase 25). Run in Supabase SQL Editor after public.trucks exists.

create table if not exists public.fleet_reminders (
    id bigint generated by default as identity primary key,
    truck_id bigint not null references public.trucks (id) on delete cascade,
    reminder_type text not null,
    target_value text not null,
    email text not null,
    notes text not null default '',
    is_resolved boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists fleet_reminders_truck_id_idx on public.fleet_reminders (truck_id);
create index if not exists fleet_reminders_is_resolved_idx on public.fleet_reminders (is_resolved);

alter table public.fleet_reminders enable row level security;

drop policy if exists "fleet_reminders_authenticated_full_access" on public.fleet_reminders;

create policy "fleet_reminders_authenticated_full_access"
    on public.fleet_reminders
    for all
    to authenticated
    using (true)
    with check (true);
