-- Trip profitability rows (Phase 14). Run in Supabase SQL Editor after trucks exists.

create table if not exists public.trip_financials (
    id bigint generated by default as identity primary key,
    truck_id bigint not null references public.trucks (id) on delete cascade,
    trip_date date not null,
    start_location text not null,
    end_location text not null,
    revenue numeric(14, 4) not null check (revenue >= 0),
    fuel_litres numeric(14, 4) not null check (fuel_litres >= 0),
    fuel_rate numeric(14, 4) not null check (fuel_rate >= 0),
    other_expenses numeric(14, 4) not null default 0 check (other_expenses >= 0),
    created_at timestamptz not null default now()
);

alter table public.trip_financials enable row level security;

drop policy if exists "trip_financials_authenticated_full_access" on public.trip_financials;

create policy "trip_financials_authenticated_full_access"
    on public.trip_financials
    for all
    to authenticated
    using (true)
    with check (true);
