-- Trucks + trip_logs with RLS (authenticated full access).
-- Requires public.drivers (see sql/drivers.sql). Run in Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- TRUCKS
-- ---------------------------------------------------------------------------
create table if not exists public.trucks (
    id bigint generated by default as identity primary key,
    truck_number text not null,
    driver_id bigint not null references public.drivers (id) on delete restrict,
    chassis_number text not null,
    registration_plate text not null,
    car_model text not null,
    driver_contact text not null,
    tank_count integer not null check (tank_count in (1, 2)),
    total_tank_capacity numeric(14, 4) not null check (total_tank_capacity > 0),
    created_at timestamptz not null default now(),
    unique (truck_number)
);

create index if not exists idx_trucks_driver_id on public.trucks (driver_id);

-- ---------------------------------------------------------------------------
-- TRIP LOGS
-- ---------------------------------------------------------------------------
create table if not exists public.trip_logs (
    id bigint generated by default as identity primary key,
    truck_id bigint not null references public.trucks (id) on delete cascade,
    start_odometer numeric(14, 4) not null,
    end_odometer numeric(14, 4) not null,
    distance_covered numeric(14, 4) not null,
    expected_fuel_consumption numeric(14, 4) not null,
    actual_fuel_consumption numeric(14, 4) not null default 0,
    refuel_amount numeric(14, 4) not null default 0,
    remaining_fuel numeric(14, 4) not null,
    fuel_percentage_used numeric(14, 4) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_trip_logs_truck_id on public.trip_logs (truck_id);
create index if not exists idx_trip_logs_truck_created on public.trip_logs (truck_id, created_at desc);

-- ---------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
alter table public.trucks enable row level security;
alter table public.trip_logs enable row level security;

-- Drop legacy policy names if you previously ran an older version of this script:
drop policy if exists "trucks_select_authenticated" on public.trucks;
drop policy if exists "trucks_insert_authenticated" on public.trucks;
drop policy if exists "trucks_update_authenticated" on public.trucks;
drop policy if exists "trucks_delete_authenticated" on public.trucks;
drop policy if exists "trip_logs_select_authenticated" on public.trip_logs;
drop policy if exists "trip_logs_insert_authenticated" on public.trip_logs;
drop policy if exists "trip_logs_update_authenticated" on public.trip_logs;
drop policy if exists "trip_logs_delete_authenticated" on public.trip_logs;
drop policy if exists "trucks_authenticated_full_access" on public.trucks;
drop policy if exists "trip_logs_authenticated_full_access" on public.trip_logs;

create policy "trucks_authenticated_full_access"
    on public.trucks
    for all
    to authenticated
    using (true)
    with check (true);

create policy "trip_logs_authenticated_full_access"
    on public.trip_logs
    for all
    to authenticated
    using (true)
    with check (true);
